---
extends: airbnb
ecmaFeatures:
  modules: true
env:
  browser: true
  node: true
parser: babel-eslint
rules:
  semi: 1
  quotes:
  - 2
  - single
  no-use-before-define: 0
  padded-blocks: 0
  space-before-function-paren: 0
  comma-dangle: 0
  id-length:
  - 1
  - min: 3
    max: 30
    properties: never
    exceptions:
    - x
    - y
    - vx
    - vy
    - id
    - i
    - e
    - fn
    - el
    - _
  no-unused-vars: 2
  no-unused-expressions: 0
  indent: 1
  object-curly-spacing: 0
  no-multi-spaces: 1
